apiVersion: v1
kind: Pod
metadata:
  name: stress-cpu
  namespace: default
spec:
  containers:
  - name: stress
    image: busybox
    command: ["stress"]
    args: ["-c", "100"]
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "1" 



sudo amazon-linux-extras install epel -y
sudo yum install stress -y
